import = ["~/.config/alacritty/themes/themes/solarized_dark.toml"]

[window]
padding = { x = 6, y = 6 }
opacity = 0.999

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
size = 16

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
